-- MySQL Script generated by MySQL Workbench
-- Wed Oct  2 13:45:38 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Banco
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Banco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Banco` ;
USE `Banco` ;

-- -----------------------------------------------------
-- Table `Banco`.`sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Banco`.`sucursal` (
  `nombre_sucursal` CHAR(40) NOT NULL,
  `ciudad_sucursal` VARCHAR(45) NULL DEFAULT NULL,
  `activos` INT NULL DEFAULT NULL,
  PRIMARY KEY (`nombre_sucursal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Banco`.`cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Banco`.`cuenta` (
  `numero_cuenta` CHAR(10) NOT NULL,
  `sucursal_nombre_sucursal` CHAR(40) NOT NULL,
  `saldo` INT NULL DEFAULT NULL,
  PRIMARY KEY (`numero_cuenta`),
  INDEX `fk_cuenta_sucursal_idx` (`sucursal_nombre_sucursal` ASC) VISIBLE,
  CONSTRAINT `fk_cuenta_sucursal`
    FOREIGN KEY (`sucursal_nombre_sucursal`)
    REFERENCES `Banco`.`sucursal` (`nombre_sucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Banco`.`prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Banco`.`prestamo` (
  `numero_prestamo` CHAR(10) NOT NULL,
  `sucursal_nombre_sucursal` CHAR(40) NOT NULL,
  `importe` INT NULL DEFAULT NULL,
  PRIMARY KEY (`numero_prestamo`),
  INDEX `fk_prestamo_sucursal1_idx` (`sucursal_nombre_sucursal` ASC) VISIBLE,
  CONSTRAINT `fk_prestamo_sucursal1`
    FOREIGN KEY (`sucursal_nombre_sucursal`)
    REFERENCES `Banco`.`sucursal` (`nombre_sucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Banco`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Banco`.`cliente` (
  `nombre_cliente` CHAR(50) NOT NULL,
  `calle_cliente` VARCHAR(45) NULL DEFAULT NULL,
  `ciudad_cliente` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`nombre_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Banco`.`impositor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Banco`.`impositor` (
  `cliente_nombre_cliente` CHAR(50) NOT NULL,
  `cuenta_numero_cuenta` CHAR(10) NOT NULL,
  INDEX `fk_impositor_cuenta1_idx` (`cuenta_numero_cuenta` ASC) VISIBLE,
  INDEX `fk_impositor_cliente1_idx` (`cliente_nombre_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_impositor_cuenta1`
    FOREIGN KEY (`cuenta_numero_cuenta`)
    REFERENCES `Banco`.`cuenta` (`numero_cuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_impositor_cliente1`
    FOREIGN KEY (`cliente_nombre_cliente`)
    REFERENCES `Banco`.`cliente` (`nombre_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Banco`.`prestatario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Banco`.`prestatario` (
  `cliente_nombre_cliente` CHAR(50) NOT NULL,
  `prestamo_numero_prestamo` CHAR(10) NOT NULL,
  INDEX `fk_prestatario_prestamo1_idx` (`prestamo_numero_prestamo` ASC) VISIBLE,
  INDEX `fk_prestatario_cliente1_idx` (`cliente_nombre_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_prestatario_prestamo1`
    FOREIGN KEY (`prestamo_numero_prestamo`)
    REFERENCES `Banco`.`prestamo` (`numero_prestamo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prestatario_cliente1`
    FOREIGN KEY (`cliente_nombre_cliente`)
    REFERENCES `Banco`.`cliente` (`nombre_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
